# Generated by Django 3.1.2 on 2020-11-02 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_posts_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='profile',
            new_name='author',
        ),
    ]
