# Generated by Django 3.1.3 on 2020-11-02 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20201102_1934'),
        ('main_app', '0006_auto_20201102_2323'),
    ]

    operations = [
    ]
