# Generated by Django 3.1.2 on 2020-11-05 00:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_auto_20201104_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.city'),
            preserve_default=False,
        ),
    ]
