# Generated by Django 3.1.2 on 2020-11-05 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_profile_pic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
