# Generated by Django 3.1.2 on 2020-11-05 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_delete_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='blurb',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='city',
            name='language',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
