# Generated by Django 3.1.2 on 2020-11-05 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_delete_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.ImageField(null=True, upload_to='pic'),
        ),
    ]
