# Generated by Django 3.1.2 on 2020-11-06 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_auto_20201105_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.ImageField(null=True, upload_to='static/images'),
        ),
    ]
