# Generated by Django 3.1.2 on 2020-11-05 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0016_auto_20201105_2125'),
        ('main_app', '0016_comment'),
    ]

    operations = [
    ]
