# Generated by Django 3.1.2 on 2020-11-06 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_merge_20201105_2340'),
        ('main_app', '0018_auto_20201106_0027'),
    ]

    operations = [
    ]
