# Generated by Django 3.1.2 on 2020-11-06 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_merge_20201106_0113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='pic',
        ),
    ]
