# Generated by Django 3.1.2 on 2020-11-06 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_merge_20201106_1520'),
        ('main_app', '0020_remove_profile_pic'),
    ]

    operations = [
    ]
